name: marks-file-create
dependencies:
  # Dependencies
  - pandas=1.5.1
  # Development
  - black
  - darglint
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-docstrings
  - flake8-rst-docstrings
  - isort
  - mypy
  - pep8-naming
